const MS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;

const RUNS_REFETCH_SECONDS = 15;
const DLQ_REFETCH_SECONDS = 30;
const DASHBOARD_REFETCH_SECONDS = 15;
const STATS_REFETCH_SECONDS = 30;
const SUBJECTS_REFETCH_SECONDS = 30;
const LIVE_FEED_REFETCH_SECONDS = 5;
const COLLECTORS_LIST_REFETCH_SECONDS = 60;
const HEALTH_REFETCH_SECONDS = 60;

export const MS_PER_MINUTE = SECONDS_PER_MINUTE * MS_PER_SECOND;
export const MS_PER_HOUR = SECONDS_PER_MINUTE * MS_PER_MINUTE;

export const RUNS_REFETCH_INTERVAL_MS = RUNS_REFETCH_SECONDS * MS_PER_SECOND;
export const DLQ_REFETCH_INTERVAL_MS = DLQ_REFETCH_SECONDS * MS_PER_SECOND;
export const DASHBOARD_REFETCH_INTERVAL_MS =
  DASHBOARD_REFETCH_SECONDS * MS_PER_SECOND;
export const STATS_REFETCH_INTERVAL_MS = STATS_REFETCH_SECONDS * MS_PER_SECOND;
export const SUBJECTS_REFETCH_INTERVAL_MS =
  SUBJECTS_REFETCH_SECONDS * MS_PER_SECOND;
export const LIVE_FEED_REFETCH_INTERVAL_MS =
  LIVE_FEED_REFETCH_SECONDS * MS_PER_SECOND;
export const COLLECTORS_LIST_REFETCH_INTERVAL_MS =
  COLLECTORS_LIST_REFETCH_SECONDS * MS_PER_SECOND;
export const HEALTH_REFETCH_INTERVAL_MS =
  HEALTH_REFETCH_SECONDS * MS_PER_SECOND;

export const DEFAULT_RUN_LIMIT = 100;
export const DASHBOARD_RUN_LIMIT = 20;
export const DEFAULT_DLQ_LIMIT = 100;
export const DASHBOARD_DLQ_LIMIT = 5;

const PAGE_SIZE_TINY = 10;
const PAGE_SIZE_SMALL = 20;
const PAGE_SIZE_MEDIUM = 50;
const PAGE_SIZE_LARGE = 100;

export const DEFAULT_PAYLOAD_PAGE_SIZE = PAGE_SIZE_SMALL;
export const PAYLOAD_PAGE_SIZE_OPTIONS = [
  PAGE_SIZE_TINY,
  PAGE_SIZE_SMALL,
  PAGE_SIZE_MEDIUM,
  PAGE_SIZE_LARGE,
] as const;
export const FLOW_CHART_BUCKET_LIMIT = 500;

export const HOURS_PER_DAY = 24;
